// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bmi_berechnung.proto

// Protobuf Java Version: 3.25.6
package bmi;

public final class BmiBerechnung {
  private BmiBerechnung() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BmiEingabeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bmi.BmiEingabe)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float gewicht_kg = 1;</code>
     * @return The gewichtKg.
     */
    float getGewichtKg();

    /**
     * <code>float koerpergroesse_cm = 2;</code>
     * @return The koerpergroesseCm.
     */
    float getKoerpergroesseCm();
  }
  /**
   * <pre>
   * Nachricht für die Eingabeparameter der BMI-Berechnung
   * </pre>
   *
   * Protobuf type {@code bmi.BmiEingabe}
   */
  public static final class BmiEingabe extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bmi.BmiEingabe)
      BmiEingabeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BmiEingabe.newBuilder() to construct.
    private BmiEingabe(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BmiEingabe() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BmiEingabe();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bmi.BmiBerechnung.internal_static_bmi_BmiEingabe_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bmi.BmiBerechnung.internal_static_bmi_BmiEingabe_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bmi.BmiBerechnung.BmiEingabe.class, bmi.BmiBerechnung.BmiEingabe.Builder.class);
    }

    public static final int GEWICHT_KG_FIELD_NUMBER = 1;
    private float gewichtKg_ = 0F;
    /**
     * <code>float gewicht_kg = 1;</code>
     * @return The gewichtKg.
     */
    @java.lang.Override
    public float getGewichtKg() {
      return gewichtKg_;
    }

    public static final int KOERPERGROESSE_CM_FIELD_NUMBER = 2;
    private float koerpergroesseCm_ = 0F;
    /**
     * <code>float koerpergroesse_cm = 2;</code>
     * @return The koerpergroesseCm.
     */
    @java.lang.Override
    public float getKoerpergroesseCm() {
      return koerpergroesseCm_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(gewichtKg_) != 0) {
        output.writeFloat(1, gewichtKg_);
      }
      if (java.lang.Float.floatToRawIntBits(koerpergroesseCm_) != 0) {
        output.writeFloat(2, koerpergroesseCm_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(gewichtKg_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, gewichtKg_);
      }
      if (java.lang.Float.floatToRawIntBits(koerpergroesseCm_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, koerpergroesseCm_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bmi.BmiBerechnung.BmiEingabe)) {
        return super.equals(obj);
      }
      bmi.BmiBerechnung.BmiEingabe other = (bmi.BmiBerechnung.BmiEingabe) obj;

      if (java.lang.Float.floatToIntBits(getGewichtKg())
          != java.lang.Float.floatToIntBits(
              other.getGewichtKg())) return false;
      if (java.lang.Float.floatToIntBits(getKoerpergroesseCm())
          != java.lang.Float.floatToIntBits(
              other.getKoerpergroesseCm())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GEWICHT_KG_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getGewichtKg());
      hash = (37 * hash) + KOERPERGROESSE_CM_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getKoerpergroesseCm());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bmi.BmiBerechnung.BmiEingabe parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bmi.BmiBerechnung.BmiEingabe parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bmi.BmiBerechnung.BmiEingabe parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bmi.BmiBerechnung.BmiEingabe parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bmi.BmiBerechnung.BmiEingabe parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bmi.BmiBerechnung.BmiEingabe parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bmi.BmiBerechnung.BmiEingabe parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bmi.BmiBerechnung.BmiEingabe parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static bmi.BmiBerechnung.BmiEingabe parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static bmi.BmiBerechnung.BmiEingabe parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bmi.BmiBerechnung.BmiEingabe parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bmi.BmiBerechnung.BmiEingabe parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bmi.BmiBerechnung.BmiEingabe prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Nachricht für die Eingabeparameter der BMI-Berechnung
     * </pre>
     *
     * Protobuf type {@code bmi.BmiEingabe}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bmi.BmiEingabe)
        bmi.BmiBerechnung.BmiEingabeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bmi.BmiBerechnung.internal_static_bmi_BmiEingabe_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bmi.BmiBerechnung.internal_static_bmi_BmiEingabe_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bmi.BmiBerechnung.BmiEingabe.class, bmi.BmiBerechnung.BmiEingabe.Builder.class);
      }

      // Construct using bmi.BmiBerechnung.BmiEingabe.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        gewichtKg_ = 0F;
        koerpergroesseCm_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bmi.BmiBerechnung.internal_static_bmi_BmiEingabe_descriptor;
      }

      @java.lang.Override
      public bmi.BmiBerechnung.BmiEingabe getDefaultInstanceForType() {
        return bmi.BmiBerechnung.BmiEingabe.getDefaultInstance();
      }

      @java.lang.Override
      public bmi.BmiBerechnung.BmiEingabe build() {
        bmi.BmiBerechnung.BmiEingabe result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bmi.BmiBerechnung.BmiEingabe buildPartial() {
        bmi.BmiBerechnung.BmiEingabe result = new bmi.BmiBerechnung.BmiEingabe(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(bmi.BmiBerechnung.BmiEingabe result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.gewichtKg_ = gewichtKg_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.koerpergroesseCm_ = koerpergroesseCm_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bmi.BmiBerechnung.BmiEingabe) {
          return mergeFrom((bmi.BmiBerechnung.BmiEingabe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bmi.BmiBerechnung.BmiEingabe other) {
        if (other == bmi.BmiBerechnung.BmiEingabe.getDefaultInstance()) return this;
        if (other.getGewichtKg() != 0F) {
          setGewichtKg(other.getGewichtKg());
        }
        if (other.getKoerpergroesseCm() != 0F) {
          setKoerpergroesseCm(other.getKoerpergroesseCm());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                gewichtKg_ = input.readFloat();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 21: {
                koerpergroesseCm_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private float gewichtKg_ ;
      /**
       * <code>float gewicht_kg = 1;</code>
       * @return The gewichtKg.
       */
      @java.lang.Override
      public float getGewichtKg() {
        return gewichtKg_;
      }
      /**
       * <code>float gewicht_kg = 1;</code>
       * @param value The gewichtKg to set.
       * @return This builder for chaining.
       */
      public Builder setGewichtKg(float value) {

        gewichtKg_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>float gewicht_kg = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGewichtKg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gewichtKg_ = 0F;
        onChanged();
        return this;
      }

      private float koerpergroesseCm_ ;
      /**
       * <code>float koerpergroesse_cm = 2;</code>
       * @return The koerpergroesseCm.
       */
      @java.lang.Override
      public float getKoerpergroesseCm() {
        return koerpergroesseCm_;
      }
      /**
       * <code>float koerpergroesse_cm = 2;</code>
       * @param value The koerpergroesseCm to set.
       * @return This builder for chaining.
       */
      public Builder setKoerpergroesseCm(float value) {

        koerpergroesseCm_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float koerpergroesse_cm = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKoerpergroesseCm() {
        bitField0_ = (bitField0_ & ~0x00000002);
        koerpergroesseCm_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bmi.BmiEingabe)
    }

    // @@protoc_insertion_point(class_scope:bmi.BmiEingabe)
    private static final bmi.BmiBerechnung.BmiEingabe DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bmi.BmiBerechnung.BmiEingabe();
    }

    public static bmi.BmiBerechnung.BmiEingabe getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BmiEingabe>
        PARSER = new com.google.protobuf.AbstractParser<BmiEingabe>() {
      @java.lang.Override
      public BmiEingabe parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BmiEingabe> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BmiEingabe> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bmi.BmiBerechnung.BmiEingabe getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BmiErgebnisOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bmi.BmiErgebnis)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * z.B. 22.5
     * </pre>
     *
     * <code>float bmi_wert = 1;</code>
     * @return The bmiWert.
     */
    float getBmiWert();

    /**
     * <pre>
     * z.B. "Normalgewicht"
     * </pre>
     *
     * <code>string bmi_interpretation = 2;</code>
     * @return The bmiInterpretation.
     */
    java.lang.String getBmiInterpretation();
    /**
     * <pre>
     * z.B. "Normalgewicht"
     * </pre>
     *
     * <code>string bmi_interpretation = 2;</code>
     * @return The bytes for bmiInterpretation.
     */
    com.google.protobuf.ByteString
        getBmiInterpretationBytes();
  }
  /**
   * <pre>
   * Nachricht für das Ergebnis der BMI-Berechnung
   * </pre>
   *
   * Protobuf type {@code bmi.BmiErgebnis}
   */
  public static final class BmiErgebnis extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bmi.BmiErgebnis)
      BmiErgebnisOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BmiErgebnis.newBuilder() to construct.
    private BmiErgebnis(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BmiErgebnis() {
      bmiInterpretation_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BmiErgebnis();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bmi.BmiBerechnung.internal_static_bmi_BmiErgebnis_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bmi.BmiBerechnung.internal_static_bmi_BmiErgebnis_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bmi.BmiBerechnung.BmiErgebnis.class, bmi.BmiBerechnung.BmiErgebnis.Builder.class);
    }

    public static final int BMI_WERT_FIELD_NUMBER = 1;
    private float bmiWert_ = 0F;
    /**
     * <pre>
     * z.B. 22.5
     * </pre>
     *
     * <code>float bmi_wert = 1;</code>
     * @return The bmiWert.
     */
    @java.lang.Override
    public float getBmiWert() {
      return bmiWert_;
    }

    public static final int BMI_INTERPRETATION_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object bmiInterpretation_ = "";
    /**
     * <pre>
     * z.B. "Normalgewicht"
     * </pre>
     *
     * <code>string bmi_interpretation = 2;</code>
     * @return The bmiInterpretation.
     */
    @java.lang.Override
    public java.lang.String getBmiInterpretation() {
      java.lang.Object ref = bmiInterpretation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bmiInterpretation_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * z.B. "Normalgewicht"
     * </pre>
     *
     * <code>string bmi_interpretation = 2;</code>
     * @return The bytes for bmiInterpretation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBmiInterpretationBytes() {
      java.lang.Object ref = bmiInterpretation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bmiInterpretation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(bmiWert_) != 0) {
        output.writeFloat(1, bmiWert_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bmiInterpretation_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bmiInterpretation_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(bmiWert_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, bmiWert_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bmiInterpretation_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bmiInterpretation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bmi.BmiBerechnung.BmiErgebnis)) {
        return super.equals(obj);
      }
      bmi.BmiBerechnung.BmiErgebnis other = (bmi.BmiBerechnung.BmiErgebnis) obj;

      if (java.lang.Float.floatToIntBits(getBmiWert())
          != java.lang.Float.floatToIntBits(
              other.getBmiWert())) return false;
      if (!getBmiInterpretation()
          .equals(other.getBmiInterpretation())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BMI_WERT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBmiWert());
      hash = (37 * hash) + BMI_INTERPRETATION_FIELD_NUMBER;
      hash = (53 * hash) + getBmiInterpretation().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bmi.BmiBerechnung.BmiErgebnis parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bmi.BmiBerechnung.BmiErgebnis parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bmi.BmiBerechnung.BmiErgebnis parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bmi.BmiBerechnung.BmiErgebnis parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bmi.BmiBerechnung.BmiErgebnis parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bmi.BmiBerechnung.BmiErgebnis parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bmi.BmiBerechnung.BmiErgebnis parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bmi.BmiBerechnung.BmiErgebnis parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static bmi.BmiBerechnung.BmiErgebnis parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static bmi.BmiBerechnung.BmiErgebnis parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bmi.BmiBerechnung.BmiErgebnis parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bmi.BmiBerechnung.BmiErgebnis parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bmi.BmiBerechnung.BmiErgebnis prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Nachricht für das Ergebnis der BMI-Berechnung
     * </pre>
     *
     * Protobuf type {@code bmi.BmiErgebnis}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bmi.BmiErgebnis)
        bmi.BmiBerechnung.BmiErgebnisOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bmi.BmiBerechnung.internal_static_bmi_BmiErgebnis_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bmi.BmiBerechnung.internal_static_bmi_BmiErgebnis_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bmi.BmiBerechnung.BmiErgebnis.class, bmi.BmiBerechnung.BmiErgebnis.Builder.class);
      }

      // Construct using bmi.BmiBerechnung.BmiErgebnis.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        bmiWert_ = 0F;
        bmiInterpretation_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bmi.BmiBerechnung.internal_static_bmi_BmiErgebnis_descriptor;
      }

      @java.lang.Override
      public bmi.BmiBerechnung.BmiErgebnis getDefaultInstanceForType() {
        return bmi.BmiBerechnung.BmiErgebnis.getDefaultInstance();
      }

      @java.lang.Override
      public bmi.BmiBerechnung.BmiErgebnis build() {
        bmi.BmiBerechnung.BmiErgebnis result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bmi.BmiBerechnung.BmiErgebnis buildPartial() {
        bmi.BmiBerechnung.BmiErgebnis result = new bmi.BmiBerechnung.BmiErgebnis(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(bmi.BmiBerechnung.BmiErgebnis result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.bmiWert_ = bmiWert_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.bmiInterpretation_ = bmiInterpretation_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bmi.BmiBerechnung.BmiErgebnis) {
          return mergeFrom((bmi.BmiBerechnung.BmiErgebnis)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bmi.BmiBerechnung.BmiErgebnis other) {
        if (other == bmi.BmiBerechnung.BmiErgebnis.getDefaultInstance()) return this;
        if (other.getBmiWert() != 0F) {
          setBmiWert(other.getBmiWert());
        }
        if (!other.getBmiInterpretation().isEmpty()) {
          bmiInterpretation_ = other.bmiInterpretation_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                bmiWert_ = input.readFloat();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 18: {
                bmiInterpretation_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private float bmiWert_ ;
      /**
       * <pre>
       * z.B. 22.5
       * </pre>
       *
       * <code>float bmi_wert = 1;</code>
       * @return The bmiWert.
       */
      @java.lang.Override
      public float getBmiWert() {
        return bmiWert_;
      }
      /**
       * <pre>
       * z.B. 22.5
       * </pre>
       *
       * <code>float bmi_wert = 1;</code>
       * @param value The bmiWert to set.
       * @return This builder for chaining.
       */
      public Builder setBmiWert(float value) {

        bmiWert_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * z.B. 22.5
       * </pre>
       *
       * <code>float bmi_wert = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBmiWert() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bmiWert_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object bmiInterpretation_ = "";
      /**
       * <pre>
       * z.B. "Normalgewicht"
       * </pre>
       *
       * <code>string bmi_interpretation = 2;</code>
       * @return The bmiInterpretation.
       */
      public java.lang.String getBmiInterpretation() {
        java.lang.Object ref = bmiInterpretation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bmiInterpretation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * z.B. "Normalgewicht"
       * </pre>
       *
       * <code>string bmi_interpretation = 2;</code>
       * @return The bytes for bmiInterpretation.
       */
      public com.google.protobuf.ByteString
          getBmiInterpretationBytes() {
        java.lang.Object ref = bmiInterpretation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bmiInterpretation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * z.B. "Normalgewicht"
       * </pre>
       *
       * <code>string bmi_interpretation = 2;</code>
       * @param value The bmiInterpretation to set.
       * @return This builder for chaining.
       */
      public Builder setBmiInterpretation(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        bmiInterpretation_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * z.B. "Normalgewicht"
       * </pre>
       *
       * <code>string bmi_interpretation = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBmiInterpretation() {
        bmiInterpretation_ = getDefaultInstance().getBmiInterpretation();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * z.B. "Normalgewicht"
       * </pre>
       *
       * <code>string bmi_interpretation = 2;</code>
       * @param value The bytes for bmiInterpretation to set.
       * @return This builder for chaining.
       */
      public Builder setBmiInterpretationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        bmiInterpretation_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bmi.BmiErgebnis)
    }

    // @@protoc_insertion_point(class_scope:bmi.BmiErgebnis)
    private static final bmi.BmiBerechnung.BmiErgebnis DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bmi.BmiBerechnung.BmiErgebnis();
    }

    public static bmi.BmiBerechnung.BmiErgebnis getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BmiErgebnis>
        PARSER = new com.google.protobuf.AbstractParser<BmiErgebnis>() {
      @java.lang.Override
      public BmiErgebnis parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BmiErgebnis> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BmiErgebnis> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bmi.BmiBerechnung.BmiErgebnis getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bmi_BmiEingabe_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bmi_BmiEingabe_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bmi_BmiErgebnis_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bmi_BmiErgebnis_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024bmi_berechnung.proto\022\003bmi\";\n\nBmiEingab" +
      "e\022\022\n\ngewicht_kg\030\001 \001(\002\022\031\n\021koerpergroesse_" +
      "cm\030\002 \001(\002\";\n\013BmiErgebnis\022\020\n\010bmi_wert\030\001 \001(" +
      "\002\022\032\n\022bmi_interpretation\030\002 \001(\t2=\n\tBmiDien" +
      "st\0220\n\013BerechneBmi\022\017.bmi.BmiEingabe\032\020.bmi" +
      ".BmiErgebnisb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_bmi_BmiEingabe_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bmi_BmiEingabe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bmi_BmiEingabe_descriptor,
        new java.lang.String[] { "GewichtKg", "KoerpergroesseCm", });
    internal_static_bmi_BmiErgebnis_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bmi_BmiErgebnis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bmi_BmiErgebnis_descriptor,
        new java.lang.String[] { "BmiWert", "BmiInterpretation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
